[package]
name = "bridge"
version = "0.1.0"
authors = ["Matteo Giachino <matteog@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.6", features = ["json", "blocking"] }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
thiserror = "1.0.20"
uuid = { version = "^0.7", features = ["serde", "v4"] }

[dev-dependencies]
mockito = "0.25.2"