[package]
name = "bridge"
version = "0.1.0"
authors = ["Matteo Giachino <matteog@gmail.com>"]
edition = "2018"

[features]
default = ["async"]
blocking = ["reqwest/blocking"]
async = ["reqwest", "futures-util"]

[dependencies]
reqwest = { version = "0.10.6", features = ["json", "blocking"], optional = true }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
thiserror = "1.0.20"
uuid = { version = "^0.7", features = ["serde", "v4"] }
futures-util = { version = "0.3", optional = true }

[dev-dependencies]
mockito = "0.25.2"